apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-app-monitor
  namespace: monitoring
  labels:
    release: monitoring-stack 
spec:
  selector:
    matchLabels:
      app: flask-app 
  endpoints:
  - port: metrics
    path: /metrics 
    interval: 15s 
  namespaceSelector:
    matchNames:
      - default 